src/Entity/Bill.php
<?php

namespace App\Entity;

use App\Repository\BillRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BillRepository::class)]
class Bill
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'bills')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $id_user = null;

    #[ORM\ManyToOne(inversedBy: 'bills')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Car $id_car = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdCar(): ?Car
    {
        return $this->id_car;
    }

    public function setIdCar(?Car $id_car): self
    {
        $this->id_car = $id_car;

        return $this;
    }

    public function getCreatedAt()
    {
        $created = date('d/m/Y H:m:s' ,$this->createdAt->getTimestamp());
        return $created;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'id_user', targetEntity: Bill::class, orphanRemoval: true)]
    private Collection $bills;

    #[ORM\OneToMany(mappedBy: 'owner', targetEntity: Car::class, orphanRemoval: true)]
    private Collection $cars;


    public function __construct()
    {
        $this->bills = new ArrayCollection();
        $this->cars = new ArrayCollection();
    }
    public function __toString() {
        return $this->username;
    }
    


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Bill>
     */
    public function getBills(): Collection
    {
        return $this->bills;
    }

    public function addBill(Bill $bill): self
    {
        if (!$this->bills->contains($bill)) {
            $this->bills->add($bill);
            $bill->setIdUser($this);
        }

        return $this;
    }

    public function removeBill(Bill $bill): self
    {
        if ($this->bills->removeElement($bill)) {
            // set the owning side to null (unless already changed)
            if ($bill->getIdUser() === $this) {
                $bill->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Car>
     */
    public function getCars(): Collection
    {
        return $this->cars;
    }

    public function addCar(Car $car): self
    {
        if (!$this->cars->contains($car)) {
            $this->cars->add($car);
            $car->setOwner($this);
        }

        return $this;
    }

    public function removeCar(Car $car): self
    {
        if ($this->cars->removeElement($car)) {
            // set the owning side to null (unless already changed)
            if ($car->getOwner() === $this) {
                $car->setOwner(null);
            }
        }

        return $this;
    }
}

src/Controller/BillController.php
<?php

namespace App\Controller;

use App\Entity\Bill;
use App\Entity\Car;
use App\Service\SoluPDF;
use DateTimeImmutable;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Dompdf\Dompdf;
use Dompdf\Options;
use Fpdf\Fpdf;
use Mpdf\Mpdf;
use Spatie\Browsershot\Browsershot;
use Symfony\Bundle\TwigBundle\DependencyInjection\Compiler\TwigEnvironmentPass;
use Symfony\Component\HttpFoundation\Response;

class BillController extends AbstractController
{
    #[Route('/user/bill/create', name: 'bill_create')]
    public function index(Car $car, EntityManagerInterface $em)
    {
        $user = $this->getUser();
        $bill = new Bill();
        $bill
            ->setIdCar($car)
            ->setIdUser($user)
            ->setCreatedAt(new DateTimeImmutable('now'));

        $em->persist($bill);
        try {
            $em->flush();
        } catch (\Throwable $th) {
            $this
                ->addFlash(
                    'error',
                    'Algo fue mal'
                );
        }
        return $this->redirectToRoute('user_index');
    }

    #[Route('/user/bill/getBills', name: 'bill_user')]
    public function getBills()
    {
        $bills = $this->getUser()->getBills();
        return $this->render('/user/bill/index.html.twig',[
            'bills' => $bills,
            'owner' => false
        ]);
    }

    #[Route('/user/bill/list', name: 'bill_list')]
    public function listBills(Pdf $pdf)
    {
        $bills = $this->getUser()->getBills();
        $data = [
            'bills' => $bills,
            'user' => $this->getUser(),
            'owner' => false,
        ];

        $html = $this->renderView('/user/bill/list.html.twig', $data);
        $pdf = $pdf->getOutputFromHtml($html);
        return new PdfResponse(
            $pdf,
        );
    }




    #[Route('/user/bill/all', name: 'bill_all')]
    public function allBills(Pdf $pdf)
    {
        $bills = $this->getUser()->getBills();
        $data = [
            'bills' => $bills,
            'user'  => $this->getUser(),
            'owner' => false, 
        ];

        $html = $this->renderView('/user/bill/all.html.twig', $data);
        $pdf->setOption('enable-local-file-access', true);
        $pdf = $pdf->getOutputFromHtml($html);

        return new PdfResponse(
            $pdf,
            'TodasLasFacturas.pdf'
        );

    }

    /**
     * Undocumented function
     *
     * @return void
     */
    #[Route('/user/bill/MPDF', name: 'mpdf_bill')]
    public function pruebaMpdf()
    {
        
        $mpdf = new Mpdf();
        $bills = $this->getUser()->getBills();
        $data = [
            'bills' => $bills,
            'user'  => $this->getUser(),
            'owner' => false, 
        ];


        
        $mpdf->WriteHTML($html,\Mpdf\HTMLParserMode::HTML_BODY );

        $mpdf->Output();


    }


    #[Route('/user/bill/dompdf', name: 'bill_dompdf')]
    public function dmpf()
    {
        $options = new Options();
        $options->set('isRemoteEnabled', true);
        $pdf = new Dompdf($options);
        $bills = $this->getUser()->getBills();
        $data = [
            'bills' => $bills,
            'user'  => $this->getUser(),
            'owner' => false, 
        ];

        $html = $this->renderView('/user/bill/invoice.html.twig', $data);


        $pdf->loadHtml($html);

        
        $pdf->render();

        
        $pdf->stream("DOMPDF.pdf", [
            "Attachment" => false
        ]);    
         
/*          return $this->render('/user/bill/dompdf.html.twig',$data);   */
    }


    #[Route('/user/bill/puro' , name: 'purecss')]
    public function pure()
    {
        return $this->render('/user/bill/invoice.html.twig',[
            
        ]);
    }




    /**
     * 
     */
    #[Route('/user/bill/{id}', name:'bill_pdf')]
    public function toPdf(Bill $bill, Pdf $pdf)
    {
        $data = [
            'bill'  =>  $bill,
            'user'  =>  $bill->getIdUser(),
            'car'   =>  $bill->getIdCar(),
        ];
        $html =  $this->renderView('/user/bill/download.html.twig', $data);
        $pdf->setOption('enable-local-file-access', true);
        $pdf = $pdf->getOutputFromHtml($html);
        

        return new PdfResponse(
            $pdf,
        );

    }

        //TODO:: REVISAR !!!

        #[Route('/user/bill/car/{id}', name: 'bill_car')]
        public function getCarBill(Car $car)
        {
            $bills = $car->getBills();
    
            return $this->render('/user/bill/index.html.twig', [
                'bills' => $bills,
                'owner' => true
            ]);
        }


}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\Type\CarType;
use ArrayAccess;

class UserController extends AbstractController
{
    #[Route('/user', name: 'user_index')]
    public function index(Request $req): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => $req->getSession()->get('username'),
        ]);
    }

    #[Route('/user/cars', name: 'user_get_cars' )]
    public function getCars() 
    {
        return $this->redirectToRoute('cars');
    }

    #[Route('/user/bill', name: 'user_bill')]
    public function getBills()
    {
        return $this->redirectToRoute('bill_user');
    }

    #[IsGranted('ROLE_ADMIN', message: 'You are not allowed to access the admin dashboard.')]
    #[Route('/admin', name: 'admin_index')]
    public function admin(Request $req)
    {
        return $this->render('user/index.html.twig', [




        ]);
    }
}

templates/user/bill/all.html.twig
{% extends '/user/down.base.html.twig' %}
{% block title %}
	Todas las facturas
{% endblock %}
{% block styles %}
	<style>
		html,
		body {
			height: 100%;
		}

		@media print {
			.bottom {
				page-break-after: always;
			}
		}
        tr {
            line-height: 0.5em;
        }

        .bottom {
            position: relative;
            bottom:0;
        }

        .space {
            height: 42%;
        }

	</style>
{% endblock %}
{% block body %}
	{% for bill in bills %}
		<div class="container  border border-5 h-100">
			<div class="row d-flex justify-content-around m-2">
				<div class="col-3 text-center">
					<img src="{{ absolute_url(asset('img/RC.png')) }}" class="img-fluid wh-50 rounded-top" alt=""/>
				</div>
				<div class="col-3 border border-2 pt-3">
					<p>
						<strong>Empresa:</strong>RentACar S.L.</p>
					<p>
						<strong>CIF:</strong>
						B-79949947
					</p>
					<p>
						<strong>Ubicación:
						</strong>
						Calle Cualquiera Nº 12 11540 Sanlúcar de
																								        Barrameda
					</p>
				</div>
			</div>
			<hr/>
			<div class="d-flex row justify-content-around mt-4">
				<div class="col-5 fs-1 fw-bolder">
					<h1 class="text-decoration-underline">Datos del cliente</h1>
				</div>
				<div class="col-5">
					<div class="row">
						<div class="col-6 fs-4 fw-bold">
							Nombre:
						</div>
						<div class="col-6">
							{{ user.name }}
						</div>
					</div>
					<div class="row ">
						<div class="col-6 fs-4 fw-bold">
							Nickname:
						</div>
						<div class="col-6">
							{{ user.username}}
						</div>
					</div>
				</div>
			</div>
			<hr/>
			<div class="row ">
				<div class="col-11  ms-2">
					<div class="table-responsive">
						<table class="table table-striped
										table-hover
										table-borderless
										table-secondary
									    align-middle">
							<thead class="table-light">
								<caption>Vehículo propiedad de:
									{{bill.getIdCar.getOwner}}</caption>
								<tr>
									<th>Precio</th>
									<th></th>
									<th></th>
									<th class="text-end">{{bill.getIdCar.price}}
										€</th>
								</tr>
							</thead>
							<tbody class="table-group-divider">
								<tr class="table-secondary">
									<td scope="row">Marca</td>
									<td></td>
									<td>{{bill.getIdCar.brand}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Modelo</td>
									<td></td>
									<td>{{bill.getIdCar.model}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Matrícula</td>
									<td></td>
									<td>{{bill.getIdCar.plate}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Kilómetros</td>
									<td></td>
									<td>{{bill.getIdCar.km?:'Desconocido'}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Motor</td>
									<td></td>
									<td>{{bill.getIdCar.engine?:'Desconocido'}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Color</td>
									<td></td>
									<td>{{bill.getIdCar.color?:'Desconocido'}}</td>
									<td></td>
								</tr>
							</tbody>
							<tfoot></tfoot>
						</table>
					</div>
				</div>
			</div>
            <div class="row space"></div>
			<div class="row bottom-0">
				<div class="bottom w-100">
					<div class="row">
						<div class="col-5"></div>
						<div class="col-2 ">
							<img src="https://i.ibb.co/Gpv3KwY/RC.png" class="img-fluid rounded-top opacity-50" alt=""/>
						</div>
						<div class="col-4"></div>
						<div class="col-1 bottom-0 d-flex justify-content-end flex-row-reverse  align-items-end ">
							<div>
								<p class="mt-auto mb-0">
									Pag
									{{loop.index}}
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}

{% endblock %}

templates/user/bill/dompdf.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8"/>
		<title>
			{% block title %}RentACar
			{% endblock %}
		</title>
		<link
		rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>"/>
		{# Run `composer require symfony/webpack-encore-bundle` to start using
				    Symfony UX #}

			{{ encore_entry_link_tags("app")  }}
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"/>
			<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
			<style>
				html,
				body {
					height: 100%;
				}

				@media print {
					.bottom {
						page-break-after: always;
					}
				}
				tr {
					line-height: 0.5em;
				}

				.bottom {
					position: relative;
					bottom: 0;
				}

				.space {
					height: 42%;
				}
			</style>



	</head>
	<body>



	{% for bill in bills %}
		<div class="  border border-5 h-100">
			<div class="row d-flex justify-content-around m-2">
				<div class="col-3 text-center">
					<img src="{{ absolute_url(asset('img/RC.jpg')) }}" class="img-fluid wh-50 rounded-top" alt="" {# style="width:25%" #}/>
				</div>
				<div class="col-3  pt-3">
					<p>
						<strong>Empresa:</strong>RentACar S.L.</p>
					<p>
						<strong>CIF:</strong>
						B-79949947
					</p>
					<p>
						<strong>Ubicación:
						</strong>
						Calle Cualquiera Nº 12 11540 Sanlúcar de
																																																        Barrameda
					</p>
				</div>
			</div>
			<hr/>
			<div class="d-flex row justify-content-around mt-4">
				<div class="col-5 fs-1 fw-bolder">
					<h1 class="text-decoration-underline">Datos del cliente</h1>
				</div>
				<div class="col-5">
					<div class="row">
						<div class="col-6 fs-4 fw-bold">
							Nombre:
						</div>
						<div class="col-6">
							{{ user.name }}
						</div>
					</div>
					<div class="row ">
						<div class="col-6 fs-4 fw-bold">
							Nickname:
						</div>
						<div class="col-6">
							{{ user.username}}
						</div>
					</div>
				</div>
			</div>
			<hr/>
			<div class="row ">
				<div class="col-11  ms-2">
					<div class="table-responsive">
						<table class="table table-striped table-hover table-borderless table-secondary align-middle">
							<thead class="table-light">
								<caption>Vehículo propiedad de:
									{{bill.getIdCar.getOwner}}</caption>
								<tr>
									<th>Precio</th>
									<th></th>
									<th></th>
									<th class="text-end">{{bill.getIdCar.price}}
										€</th>
								</tr>
							</thead>
							<tbody class="table-group-divider">
								<tr class="table-secondary">
									<td scope="row">Marca</td>
									<td></td>
									<td>{{bill.getIdCar.brand}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Modelo</td>
									<td></td>
									<td>{{bill.getIdCar.model}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Matrícula</td>
									<td></td>
									<td>{{bill.getIdCar.plate}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Kilómetros</td>
									<td></td>
									<td>{{bill.getIdCar.km?:'Desconocido'}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Motor</td>
									<td></td>
									<td>{{bill.getIdCar.engine?:'Desconocido'}}</td>
									<td></td>
								</tr>
								<tr class="table-secondary">
									<td scope="row">Color</td>
									<td></td>
									<td>{{bill.getIdCar.color?:'Desconocido'}}</td>
									<td></td>
								</tr>
							</tbody>
							<tfoot></tfoot>
						</table>
					</div>
				</div>
			</div>
			<div class="row space"></div>
			<div class="row bottom-0">
				<div class="bottom w-100">
					<div class="row">
						<div class="col-5"></div>
						<div class="col-2 ">
							<img src="https://i.ibb.co/Gpv3KwY/RC.png" class="img-fluid rounded-top opacity-50" alt=""/>
						</div>
						<div class="col-4"></div>
						<div class="col-1 bottom-0 d-flex justify-content-end flex-row-reverse  align-items-end ">
							<div>
								<p class="mt-auto mb-0">
									Pag
									{{loop.index}}
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}



	</body>
</html>

templates/user/bill/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RentACar
{% endblock %}
{% block body %}
		{{ include('./user/_nav.html.twig') }}



	<div class="container">
		{% for flash_message in app.session.flashbag.get('error') %}
			<div class="flash-notice">
				{{ flash_message }}
			</div>
		{% endfor %}
		
		<a class="btn btn-success" href="{{path('bill_list')}}">Descargar listado de Facturas </a>
		<div class="table-responsive  pt-5 ">
			<table class="table table-secondary">
				<thead>
					<tr class="">
						<th scope="row">Num Factura</th>
						<th>Coche</th>
						<th>Fecha Creación</th>
						{% if owner == true %}
							<th> Usuario </th>
						{% endif %}

						<th colspan="2" style="text-align:center">Acciones</th>
					</tr>
				</thead>
				<tbody>
					{% for bill in bills %}
						<tr class="">
							<td scope="row">
								{{bill.id}}
							</td>
							<td> <a class="link-secondary" href="{{path('car_index', {'id': bill.idCar.id})}}">
								{{bill.idCar.getBrand}} {{bill.idCar.getModel}}
								</a>	
							</td>
							<td>
								{{bill.createdAt}}</td>
						{% if owner == true %}
							<td> {{bill.idUser.username}} </td>
						{% endif %}

							<td style=" text-align: center; vertical-align: middle;">
								<a target="_blank" class="btn btn-success" href="{{path('bill_pdf', {'id': bill.id})}}">Descargar</a>
							</td>


						</tr>
					{% endfor %}
				</tbody>
			</tbody>
		</table>
		<div class="d-flex justify-content-end">
		<a href="{{path('bill_all')}}" class="btn btn-primary " >Descargar Todas las Facturas</a>
		<a class="btn btn-warning" href="{{path('bill_dompdf')}}">Descargar listado de Facturas con DOMPDF</a>
		</div>
	</div>


</div>{% endblock %}

templates/user/bill/list.html.twig
{% extends './user/down.base.html.twig' %}

{% block styles %}
<style>
  html,
  body {
    height: 100%;
  }
</style>
{% endblock %}

{% block body %}
    <div class="container border border-5  h-100">
         <div class="row d-flex justify-content-around m-2">
    <div class="col-3 text-center">
      <img
        src="https://i.ibb.co/Gpv3KwY/RC.png"
        class="img-fluid wh-50 rounded-top"
        alt=""
      />
    </div>
    <div class="col-3 border border-2 pt-3">
      <p><strong>Empresa:</strong>RentACar S.L.</p>
      <p>
        <strong>CIF:</strong>
        B-79949947
      </p>
      <p>
        <strong>Ubicación: </strong> Calle Cualquiera Nº 12 11540 Sanlúcar de
        Barrameda
      </p>
    </div>
  </div>
  <hr />
  <div class="d-flex row justify-content-around mt-4">
    <div class="col-5 fs-1 fw-bolder">
      <h1 class="text-decoration-underline">Datos del cliente</h1>
    </div>
    <div class="col-5"> 
      <div class="row">
        <div class="col-6 fs-4 fw-bold">
          Nombre:
        </div>
        <div class="col-6">
          {{ user.name }}
        </div>
      </div>
      <div class="row ">
        <div class="col-6 fs-4 fw-bold">
          Nickname:
        </div>
        <div class="col-6">
          {{ user.username}}
        </div>
      </div>
    </div>
  </div>

		<div class="table-responsive  pt-5 ">
			<table class="table table-secondary">
				<thead>
					<tr class="">
						<th scope="row">Num Factura</th>
						<th>Coche</th>
						<th>Fecha Creación</th>
						{% if owner == true %}
							<th> Usuario </th>
						{% endif %}
					</tr>
				</thead>
				<tbody>
					{% for bill in bills %}
						<tr class="">
							<td scope="row">
								<a target="_blank" class="link-dark" href="/user/bill/{{bill.id}}">{{bill.id}}</a>
							</td>
							<td> <a class="link-secondary" href="{{path('car_index', {'id': bill.idCar.id})}}">
								{{bill.idCar.getBrand}} {{bill.idCar.getModel}}
								</a>	
							</td>
							<td>
								{{bill.createdAt}}
                            </td>
						{% if owner == true %}
							<td> {{bill.idUser.username}} </td>
						{% endif %}
						</tr>
					{% endfor %}
				</tbody>
			</tbody>
		</table>

	</div>


</div>
{% endblock %}